# Generated by Django 5.2.4 on 2025-07-04 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_mod', models.CharField(max_length=30)),
                ('fecha_mod', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_mod', models.CharField(max_length=30)),
                ('fecha_mod', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('mass', models.FloatField()),
                ('hair_color', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('homeworld', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('img', models.URLField()),
                ('films', models.ManyToManyField(to='characters.film')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
